// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed img/format/code.svg
var resourceCodeSvgData []byte
var resourceCodeSvg = &fyne.StaticResource{
	StaticName:    "img/format/code.svg",
	StaticContent: resourceCodeSvgData,
}

//go:embed img/format/code_blocks.svg
var resourceCodeblocksSvgData []byte
var resourceCodeblocksSvg = &fyne.StaticResource{
	StaticName:    "img/format/code_blocks.svg",
	StaticContent: resourceCodeblocksSvgData,
}

//go:embed img/format/format_bold.svg
var resourceFormatboldSvgData []byte
var resourceFormatboldSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_bold.svg",
	StaticContent: resourceFormatboldSvgData,
}

//go:embed img/format/format_clear.svg
var resourceFormatclearSvgData []byte
var resourceFormatclearSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_clear.svg",
	StaticContent: resourceFormatclearSvgData,
}

//go:embed img/format/format_h1.svg
var resourceFormath1SvgData []byte
var resourceFormath1Svg = &fyne.StaticResource{
	StaticName:    "img/format/format_h1.svg",
	StaticContent: resourceFormath1SvgData,
}

//go:embed img/format/format_h2.svg
var resourceFormath2SvgData []byte
var resourceFormath2Svg = &fyne.StaticResource{
	StaticName:    "img/format/format_h2.svg",
	StaticContent: resourceFormath2SvgData,
}

//go:embed img/format/format_italic.svg
var resourceFormatitalicSvgData []byte
var resourceFormatitalicSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_italic.svg",
	StaticContent: resourceFormatitalicSvgData,
}

//go:embed img/format/format_list_bulleted.svg
var resourceFormatlistbulletedSvgData []byte
var resourceFormatlistbulletedSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_list_bulleted.svg",
	StaticContent: resourceFormatlistbulletedSvgData,
}

//go:embed img/format/format_list_numbered.svg
var resourceFormatlistnumberedSvgData []byte
var resourceFormatlistnumberedSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_list_numbered.svg",
	StaticContent: resourceFormatlistnumberedSvgData,
}

//go:embed img/format/format_quote.svg
var resourceFormatquoteSvgData []byte
var resourceFormatquoteSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_quote.svg",
	StaticContent: resourceFormatquoteSvgData,
}

//go:embed img/format/format_strikethrough.svg
var resourceFormatstrikethroughSvgData []byte
var resourceFormatstrikethroughSvg = &fyne.StaticResource{
	StaticName:    "img/format/format_strikethrough.svg",
	StaticContent: resourceFormatstrikethroughSvgData,
}
